server:
  host: "localhost"
  port: 5080

console:
  level: info

database:
  mongoid:
    development:
      sessions:
        default:
          database: "frecon"
          hosts:
            - "localhost:27017"

      options:
        use_utc: true
        raise_not_found_error: false

    production:
      sessions:
        default:
          database: "frecon"
          hosts:
            - "localhost:27017"

      options:
        use_utc: true
        raise_not_found_error: false
